### ISSUE TITLE
MongoKitten 5 improvements

### ISSUE THREAD

**Issue by Obbut** [orlandos-nl/MongoKitten#168]
This issue is meant for tracking the progress and goals of MongoKitten 5. The comments on this issue may be used for discussing MongoKitten 5 development.

@Joannis and I have limited time to work on MongoKitten 5. If you are a MongoKitten user, you are encouraged to help wherever possible. This issue should provide a general overview of the tasks that need to be done for MK5, but if you're not sure where you can help, feel free to comment here or reach out to one of us directly.

We documented our [general architecture](https://github.com/OpenKitten/MongoKitten/blob/master/5.0/docs/Architecture.md) and [philosophy](https://github.com/OpenKitten/MongoKitten/blob/master/5.0/docs/Philosophy.md).

## General Development Information

- Development takes place on the `master/5.0` branch
- There is no time schedule. It is done when it is done
- MongoKitten 5 is a from-the-ground-up rewrite
- The target platforms are macOS, Ubuntu versions supported by the Swift team, and iOS
- The target Swift version is 4.1 and later

## High level goals

- Remove unneeded bloat
- Fully async with Swift NIO (but with sync helpers where possible)
- Embraces Codable where applicable
- Support modern MongoDB features (change streams, new MongoDB 3.6 protocol), while providing support for MongoDB 3.2 and later

## How to help

- The most obvious way you can help is by contributing code. We will try to maintain a list of tasks in this issue
- Tests are never good enough
- Improve the documentation comments or write tutorials
- Provide us with feedback on our code and API. All feedback is very welcome, whether you think some behaviour is unexpected, not immediately obvious, code is unclear or ugly, but of course also when you do like something
- We are also looking for someone to improve our website. The website should be simple and provide links to OpenKitten projects and documentation

### Easy issues

- [x] Expose drop database and collection as a helper
- [x] Add text search helpers to Query
- [x] [Collation support](https://github.com/mongodb/specifications/blob/master/source/collation/collation.rst)

### Medium issues

- [x] Read/Write concern practical and unit tests
- [x] Respect MongoDB's 16MB query cap in [the old](https://github.com/OpenKitten/MongoKitten/blob/feature/transactions-sessions/Sources/MongoKitten/Connection.swift#L299) and [the new](https://github.com/OpenKitten/MongoKitten/blob/feature/transactions-sessions/Sources/MongoKitten/Connection.swift#L269) protocol
- [x] A proper way of dealing with protocol parsing errors [(I.E. not crashing)](https://github.com/OpenKitten/MongoKitten/blob/master/5.0/Sources/MongoKitten/Connection.swift#L359)
- [ ] A hell of a lot of documentation and unit tests

### Hard issues

- [ ] [X509 certificate based auth](https://github.com/mongodb/specifications/blob/master/source/auth/auth.rst#mongodb-x509)
- [x] [Authentication mechanism negotiation](https://github.com/mongodb/specifications/blob/master/source/auth/auth.rst#mechanism-negotiation-via-handshake)
- [x] [Automatic selection of mechanism for older servers](https://github.com/mongodb/specifications/blob/master/source/auth/auth.rst#defaults)
- [x] [MongoDB-CR auth](https://github.com/mongodb/specifications/blob/master/source/auth/auth.rst#mongodb-cr)
- [ ] [Decimal128 support in BSON](https://github.com/mongodb/specifications/blob/master/source/bson-decimal128/decimal128.rst)
- [ ] [Swift NIO ZLib compression](https://github.com/apple/swift-nio-zlib-support) for [the wire protocol](https://github.com/mongodb/specifications/blob/master/source/compression/OP_COMPRESSED.rst)

### Hardcore issues

- [x] [Sessions support in the driver](https://github.com/mongodb/specifications/blob/master/source/sessions/driver-sessions.rst)
- [x] Transactions
- [x] [Retryable writes](https://github.com/mongodb/specifications/tree/master/source/retryable-writes) dependent upon sessions
- [x] Custom Root certificates for NIO SSL (so IBM bluemix can be better supported)
- [x] [DNS based server discovery](https://github.com/mongodb/specifications/tree/master/source/initial-dns-seedlist-discovery)
- [x] [Server Discovery and Monitoring](https://github.com/mongodb/specifications/tree/master/source/server-discovery-and-monitoring)
- [x] MongoKitten internal connection pool for SDaM
- [x] [Server Selection](https://github.com/mongodb/specifications/tree/master/source/server-selection)

### Internal research points

- [x] [Casual Consistency](https://github.com/mongodb/specifications/blob/master/source/causal-consistency/causal-consistency.rst)

**Comment by Joannis** [comment]
The remainder of open points are relatively little work. Since MongoKitten 5 is released this implies these points are not (completely) done yet. If you're unsure how to help out with one or more of these points, give us a heads up in slack and we'll help you along.

**Comment by philmodin** [comment]
Is there support for Decimal128 yet? Seeing it's not checked off here and had a hard time finding any useful references in the code.
