### ISSUE TITLE
support $dateFromString operator for aggregation

### ISSUE THREAD

**Issue by popaaaandrei** [orlandos-nl/MongoKitten#210]
**Is your feature request related to a problem? Please describe.**
It would be nice if we could support the `$dateFromString` operator. It would simplify the date conversion.

https://docs.mongodb.com/manual/reference/operator/aggregation/dateFromString/

**Comment by Joannis** [comment]
Advocate of the devil here, but what prevents you from:
- Making a date locally?
- Using the operator in a "raw"/custom stage?

**Comment by popaaaandrei** [comment]
I was thinking of the ways I could speed up date conversion (Mongo native vs Vapor), but I admit I didn't read the raw docs :D
