### ISSUE TITLE
$match in ChangeStream does not work properly

### ISSUE THREAD

**Issue by devborz** [orlandos-nl/MongoKitten#283]
Hi!

When I need to get changes from specific document and I write this:
```Swift 
let loop = users.buildChangeStream {
    return AggregateBuilderStage.init(documents: [[
        "$match" : [
            "username" :  "devborz"
        ]
    ]])
}
```
ChangeStream does not react to any changes in database. I've tried to write "fullDocument.username" instead of "username" but nothing changes. 

But if I write something like this:
```Swift 
let loop = users.buildChangeStream {
    return AggregateBuilderStage.init(documents: [[
        "$match" : [
            "_id" : [
                "$exists" : true
            ]
        ]
    ]])
}
```
ChangeStream react to all changes in collection. 

Is this a bug or I am doing something wrong?

**Comment by Joannis** [comment]
Can you try using the global helper function `match("username" == "devborz")` inside the `buildChangeStream` block? `buildChangeStream` is a resultBuilder, so I'd definitely recommend using it in that way, much cleaner code :)

**Comment by Joannis** [comment]
https://github.com/orlandos-nl/MongoKitten/blob/master/6.0/Sources/MongoKitten/AggregateBuilder.swift#L99-L105

**Comment by Joannis** [comment]
Also, feel free to hop on Discord in case I forget to reply here. It is very late, so I'll probably reply in my moring.

**Comment by devborz** [comment]
Thanks for the fast reply. Tried this but still does not work
```Swift
let loop = users.buildChangeStream {
    return .match("username" == "devborz")
}
```

**Comment by Joannis** [comment]
Can you show me what your document looks like?

**Comment by devborz** [comment]
My document looks like
![Document](https://user-images.githubusercontent.com/45741674/165082220-7a6724a9-e5b1-465c-95da-0f3132973e3a.png)

**Comment by devborz** [comment]
And how should I include fullDocumen = .updateLookup option in changeStream? Like it was done here  #174

**Comment by devborz** [comment]
Fixed this by adding fullDocument field into ChangeStreamOption 👍🏻
```Swift
public struct ChangeStreamOptions: Encodable {
    private enum CodingKeys: String, CodingKey {
        case batchSize
        case collation
        case fullDocument
    }

    public var batchSize: Int32?
    public var collation: Collation?
    public var maxAwaitTimeMS: Int64?
    public var fullDocument: String?

    public init() {}
}
```
And used it like:
```Swift 
var options = ChangeStreamOptions()
options.fullDocument = "updateLookup"
let loop = users.buildChangeStream(options: options, using: .init()) {
    return .match("fullDocument.username" == "devborz")
}
```
Now 
```Swift
print(notification.fullDocument)
```
Prints document data
![Print](https://user-images.githubusercontent.com/45741674/165178856-477a0399-3622-492e-b510-b51c123eab80.png)
