### ISSUE TITLE
Cannot decode `[Date]` from Codable model

### ISSUE THREAD

**Issue by grahamburgsma** [orlandos-nl/MongoKitten#298]
**Describe the bug**
Cannot decode `[Date]` from Codable model. In my case the query is done through an aggregate pipeline.

**To Reproduce**
```swift
struct SomeModel: Codable {
  let dates: [Date]
}

let aggregate = req.mongoDB["somecollection"].buildAggregate { ... }

let results = try await aggregate.decode(SomeModel.self).drain()
```

**What happens**
Error is thrown: `[ WARNING ] BSONTypeConversionError<Primitive>(from: 2022-08-24 18:09:46 +0000, to: Swift.Double)`.

**Server-side Swift:**
- OS: macOS
 - Swift Version: 5.7
 - MongoKitten Version: 7.2.1

**Comment by Joannis** [comment]
@grahamburgsma what's your BSON version?

**Comment by grahamburgsma** [comment]
> what's your BSON version?

@Joannis It is 8.0.1.

**Comment by Joannis** [comment]
Can you update that to 8.0.2? There's a known bug in BSON when using Dates within a property wrapper on 8.0.1

**Comment by Joannis** [comment]
It might also affect other specific generics

**Comment by grahamburgsma** [comment]
8.0.2 has fixed it, thanks for the quick support!
