### ISSUE TITLE
Cannot connect to MongoAtlas DB Error: FluentMongoError.noTargetDatabaseSpecified

### ISSUE THREAD

**Issue by dennis777** [orlandos-nl/MongoKitten#327]
Basically the title, I have a working configuration of a Swift Vapor server with Fluent accessing Mongodb for my database backend and in my configure file I have this connection string which works on my local database, but does not work when I simply replace the connection string to my mongo atlas connection string. See code below

```swift
// This works
public func configure(_ app: Application) async throws {
    try app.databases.use(DatabaseConfigurationFactory.mongo(
        connectionString: "mongodb://127.0.0.1:27017/emodalFisher"
    ), as: .mongo)
}
```
```swift
// This does NOT work...?
public func configure(_ app: Application) async throws {
    try app.databases.use(DatabaseConfigurationFactory.mongo(
        connectionString: "mongodb+srv://<username>:<password>@emodalfisher.xfunryq.mongodb.net/?retryWrites=true&w=majority
    ), as: .mongo)
}
```

No, I did not forget to change `<username>` & `<password>` to my username & password in the connection string ;)

When run, the server instantly crashes with an error message FluentMongoError.noTargetDatabaseSpecified, which I assume means Fluent cannot find my database. I used `mongosh` in the terminal and was able to connect to my online database just fine so I'm not sure what's the issue. 

macOS 14.1.1
Swift 5.9
Vapor toolbox 18.7.4
Mongo 2.1.1

**Comment by Joannis** [comment]
Hello Dennis! Sorry for missing this issue, I usually scan the titles of PR issues, but since I'm not very involved with Fluent I discarded this message in my mailbox.

You'll need to put a database name behind the `/` (before the `?`)

**Comment by dennis777** [comment]
I pasted the connection string into a nodejs instance and it worked fine, so I don't think the connection string is the issue. I read online that mongodb atlas has sort of its own protocol or something. I ended up just using mongodb locally

**Comment by Joannis** [comment]
@dennis777 the connection string is fine for connecting to MongoDB. But _Fluent_ requires knowledge of what database you want to select in your MongoDB server.

**Comment by Joannis** [comment]
Also, Atlas does not have its own protocol. But it does have a different way of handling DNS

**Comment by Joannis** [comment]
`mongodb+srv://<username>:<password>@emodalfisher.xfunryq.mongodb.net/emodalFisher?retryWrites=true&w=majority`

This is your fixed URL

**Comment by dennis777** [comment]
Ahhh. Thank you! That URL works like as it should
