### ISSUE TITLE
unpin DNSClient dependency version

### ISSUE THREAD

**Issue by tayloraswift** [orlandos-nl/MongoKitten#331]
for some reason, this package’s `DNSClient` dependency was pinned to an ancient version of that repo in [`e227a4f5c86c394e0ba1adf82b7cdd1b79eca2a3`](https://github.com/orlandos-nl/MongoKitten/commit/e227a4f5c86c394e0ba1adf82b7cdd1b79eca2a3). 

https://github.com/orlandos-nl/MongoKitten/blob/18dfaa1ba9980c555a5d5ac4ff6a07ed54156d3c/Package.swift#L44

**Comment by Joannis** [comment]
Good catch! Thanks for the sharpness
