### ISSUE TITLE
Whether to support native query

### ISSUE THREAD

**Issue by onlw** [orlandos-nl/MongoKitten#333]
like 

`query(db.collection.aggregate([
  {
    $group: {
      _id: {
        machineId: "$machine.id",
        reportMonth: "$report_month"
      },
      totalValue: { $sum: "$value" }
    }
  },
  {
    $match: {
      totalValue: { $gt: 1 }
    }
  }
]))`

**Comment by Joannis** [comment]
You can use `.buildAggregate` to construct a pipeline using result builders. Then you can add your own AggregateState, an example of which is the implementation of `$match` right underneath

https://github.com/orlandos-nl/MongoKitten/blob/main/Sources/MongoKitten/AggregateStage.swift#L7C17-L29

**Comment by onlw** [comment]
Thanks for your reply, in fact, I am going to make a mongo GUI tool, the commands are assembled by the user

**Comment by onlw** [comment]
> You can use `.buildAggregate` to construct a pipeline using result builders. Then you can add your own AggregateState, an example of which is the implementation of `$match` right underneath
> 
> https://github.com/orlandos-nl/MongoKitten/blob/main/Sources/MongoKitten/AggregateStage.swift#L7C17-L29

Thanks for your reply, in fact, I am going to make a mongo GUI tool, the commands are assembled by the user

**Comment by Joannis** [comment]
@onlw using SwiftUI? I've had a similar tool as well :)

**Comment by onlw** [comment]
> @onlw using SwiftUI? I've had a similar tool as well :)

yeah, SwiftUI,  It seems that I didn't find the tool

**Comment by raffeyang** [comment]
> > @onlw using SwiftUI? I've had a similar tool as well :)使用 SwiftUI？我也有一个类似的工具:)
> 
> yeah, SwiftUI, It seems that I didn't find the tool是的，SwiftUI，看来我没有找到工具

Where can I download your app ?
