### ISSUE TITLE
Can't connect to MongoDb Online from iOS device

### ISSUE THREAD

**Issue by Begoodi** [orlandos-nl/MongoKitten#349]
I setup a connection to a MongoDB database with Mongokitten. 
This is the code I do to manage the connection :

`class MongoManager {
	static let shared = MongoManager()
	
	let connectionString = "mongodb+srv://user:password@myCluster.vd2s3.mongodb.net/mongolf?retryWrites=true&w=majority&appName=myCluster"
	var db: MongoDatabase?
	
	var isConnected: Bool {
		return db != nil
	}
	
	func connect() async {
		if isConnected {
			return
		}
		do {
			db = try await MongoDatabase.connect(to: connectionString)
			if isConnected {
				print("Connected to MongoDB")
			}
		} catch {
			print("Error Init MongoDB : \(error)")
		}
	}
}`

It works perfectly from the simulator, but from the real iOS Device I get : "Error Init MongoDB : UnableToParseConfig()"

Any idea what I could check ?
Tried so many things... thanks for your help

**Comment by Joannis** [comment]
iOS doesn't have an /etc/resolv.conf, whereas macOS (and apparently the Simulator) do. MongoKitten uses this file to find your DNS Server- which you'll need to specify manually with a query parameter.

dnsServer=1.1.1.1 for example

**Comment by Joannis** [comment]
`dnsServer`, not `dns`

https://github.com/orlandos-nl/MongoKitten/blob/cc566385d9daf214737d547b3107e7a9cee50a45/Sources/MongoCore/Primitives/ConnectionSettings.swift#L119

https://github.com/orlandos-nl/MongoKitten/blob/cc566385d9daf214737d547b3107e7a9cee50a45/Sources/MongoCore/Primitives/ConnectionSettings.swift#L320

**Comment by Begoodi** [comment]
Oups, read too fast, sorry.
Many thanks for your help  !
